### ISSUE TITLE
How about make a website to show the powerful features?

### ISSUE THREAD

**Issue by yunsii** [DreamOfIce/fastText.wasm#1]
It's so interesting, I can make it if possible.

**Comment by yunsii** [comment]
A bit embarrassed, the lib can not work with Next.js for now……

**Comment by DreamOfIce** [comment]
> the lib can not work with Next.js for now……

What's the reason? Is there an error log?

**Comment by DreamOfIce** [comment]
About the website, I plan to complete the type definition and make a document site later.

I think we can display some demos of different technology stacks(Vue/React/etc.) on that website.

Maybe you can make a demo based on React? (I mainly use Vue)

**Comment by yunsii** [comment]
> What's the reason? Is there an error log?

Server error:
![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/bc145a29-2c75-4fe9-832f-7e739bb1e9fa)

Client error:
![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/638fdd00-9c88-4527-9a1e-35b5da2430fb)

**Comment by yunsii** [comment]
Moreover, Next.js will print warning for `import(expression)`

`Critical dependency: the request of a dependency is an expression`

**Comment by yunsii** [comment]
```
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

and etc. So many questions to let it runs in Next.js, I have to create a new lib [fasttext.wasm.js](https://github.com/yunsii/fasttext.wasm.js), After strugled with various errors, it works at now 😂 Online page: https://awesome-exhibition.vercel.app/awesome/fasttext.wasm.js

**Comment by DreamOfIce** [comment]
> Server error: ![image](https://user-images.githubusercontent.com/18096089/268476374-bc145a29-2c75-4fe9-832f-7e739bb1e9fa.png)
> 
> Client error: ![image](https://user-images.githubusercontent.com/18096089/268476401-638fdd00-9c88-4527-9a1e-35b5da2430fb.png)
Sorry, I've been busy lately so I didn't reply in time.
It seems that the default model path is wrong, could you try specifying the path to `lid.176.ftz` manually?
```ts
await fastText.loadModel("path/to/lid.176.ftz") 
```

**Comment by yunsii** [comment]
![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/61022b89-f5f0-47ef-a91e-fbcfc2eea24f)
![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/b02a1874-57b7-4e62-8bbd-97841d6b54d9)

Still not work. And I created a function to normalize detected result https://github.com/yunsii/fasttext.wasm.js/blob/master/src/tools/language-identification/node.ts#L60

**Comment by DreamOfIce** [comment]
> ![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/61022b89-f5f0-47ef-a91e-fbcfc2eea24f)
> 
> ![image](https://github.com/DreamOfIce/fastText.wasm/assets/18096089/b02a1874-57b7-4e62-8bbd-97841d6b54d9)

Can you try to specify `corePath` and `wasmPath` manually? 
I'll look into improving the default path detection later.

https://github.com/DreamOfIce/fastText.wasm/blob/4cd1a246968626fe2479d05a6167a0afd99f88c5/src/options.ts#L1-L4

**Comment by yunsii** [comment]
I tried to use `fasttext.wasm/dist/core/fasttext.mjs`, encounter the same error. Next.js do not support import with variable, it must be literal.
